# Generated by Django 5.2.8 on 2026-01-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_bookingextension_coupon_customeraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)'),
        ),
    ]
